### ISSUE TITLE
ModuleNotFoundError: Module not found: Error: Can't resolve './Devtools' 

### ISSUE THREAD

**Issue by thedavidthomas** [contentstack/contentstack-gatsby-starter-app#37]
Was getting ModuleNotFoundError: Module not found: Error: Can't resolve './Devtools'  error due to this line

https://github.com/contentstack/contentstack-gatsby-starter-app/blob/8feeca46fcb04c3f508e62771283b46559aa0589/src/components/Layout.tsx#L10

Replacing with
`import DevTools from "./DevTools"`

then fixes the issue. 

The import capitalization should match the filename

**Comment by Amitkanswal** [comment]
Thanks @thedavidthomas for bringing this issue to us. We will fix this as soon as possible.
